version: "3"

networks:
  shopping-cart-backend:
    driver: bridge

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping_cart_backend
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
    user: node
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgsql
    networks:
      - shopping-cart-backend

  pgsql:
      image: postgres:12-alpine
      container_name: cart_db_1
      environment:
        POSTGRES_USER: "cart"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "cart_db"
        SERVICE_TAGS: dev
        SERVICE_NAME: pgsql
      ports:
        - "5432:5432"
      networks:
        - shopping-cart-backend

volumes:
  dbdata:
    driver: local
